ilastik:
  model: models/40x_pmc_seg.ilp
  loc: /home/dakota/Downloads/ilastik-1.3.3post3-Linux/run_ilastik.sh
input:
  logfile: /home/dakota/Data/icat_embryos/Nahomie/Nahomie_icat_embryo_log.csv
  datadir: /home/dakota/Data/icat_embryos/Nahomie
output:
  dir: data/
quant:
  genes:
    sm50:
      radius: [400, 350, 350]
    pks2:
      radius: [400, 350, 350]