ilastik:
  model: models/40x_pmc_seg.ilp
  loc: /projectnb/bradham/Ilastik/ilastik-1.3.3post3-Linux/run_ilastik.sh
input:
  logfile: files/dmso_samples.csv
  datadir: /projectnb/bradham/data/big_hcr_fish
output:
  dir: output/
quant:
  genes:
    sm50:
      radius: [400, 350, 350]
    pks2:
      radius: [400, 350, 350]